<a class=n target=content onClick="h(this);" href=/phpmyadmin/><?=$TEXT['navi-phpmyadmin']?></a><br>
<a class=n target=content onClick="h(this);" href=webalizer.php><?=$TEXT['navi-webalizer']?></a><br>
<a class=n target=content onClick="h(this);" href=mailform.php><?=$TEXT['navi-mercury']?></a><br>
<a class=n target=content onClick="h(this);" href=filezilla.php><?=$TEXT['navi-filezilla']?></a><br>
<a class=n target=content onClick="h(this);" href=jpgraph.php><?=$TEXT['navi-jpgraph']?></a>