# 
# /*
#  * *********** WARNING **************
#  * This file generated by ModPerl::WrapXS/0.01
#  * Any changes made here will be lost
#  * ***********************************
#  * 01: lib/ModPerl/Code.pm:666
#  * 02: lib/ModPerl/WrapXS.pm:506
#  * 03: lib/ModPerl/WrapXS.pm:995
#  * 04: Makefile.PL:275
#  * 05: Makefile.PL:223
#  * 06: Makefile.PL:49
#  */
# 


package Apache::Directive;


use Apache::XSLoader ();
our $VERSION = '0.01';
Apache::XSLoader::load __PACKAGE__;



1;
__END__
