# 
# /*
#  * *********** WARNING **************
#  * This file generated by ModPerl::WrapXS/0.01
#  * Any changes made here will be lost
#  * ***********************************
#  * 01: lib/ModPerl/Code.pm:666
#  * 02: G:\compile\sources\mod_perl-1.99_10/lib/ModPerl/WrapXS.pm:506
#  * 03: G:\compile\sources\mod_perl-1.99_10/lib/ModPerl/WrapXS.pm:995
#  * 04: Makefile.PL:271
#  * 05: Makefile.PL:219
#  * 06: Makefile.PL:47
#  */
# 


package Apache::SubProcess;


use Apache::XSLoader ();
our $VERSION = '0.01';
Apache::XSLoader::load __PACKAGE__;

use APR::PerlIO ();


1;
__END__
