#ifndef MODPERL_CONSTANTS_H
#define MODPERL_CONSTANTS_H

/*
 * *********** WARNING **************
 * This file generated by ModPerl::Code/0.01
 * Any changes made here will be lost
 * ***********************************
 * 01: lib/ModPerl/Code.pm:721
 * 02: lib/ModPerl/Code.pm:747
 * 03: Makefile.PL:252
 * 04: Makefile.PL:89
 */

#define MP_ENOCONST -3

SV *modperl_constants_lookup_apr(pTHX_ const char *name);
SV *modperl_constants_lookup_apache(pTHX_ const char *name);
const char **modperl_constants_group_lookup_apr(const char *name);
const char **modperl_constants_group_lookup_apache(const char *name);

#endif /* MODPERL_CONSTANTS_H */
