# 
# /*
#  * *********** WARNING **************
#  * This file generated by Apache::Build/0.01
#  * Any changes made here will be lost
#  * ***********************************
#  * 01: lib/ModPerl/Code.pm:666
#  * 02: lib/Apache/Build.pm:680
#  * 03: lib/Apache/Build.pm:1621
#  * 04: Makefile.PL:135
#  * 05: Makefile.PL:49
#  */
# 


package Apache2;

# MP_INST_APACHE2=0, do nothing

1;